/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package mx.utng.s23

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'mx.utng.s23.greeting' plugin.
 */
class TestdbPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("mx.utng.s23.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
